# Generated by Django 4.2.3 on 2023-07-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='un-Brand', max_length=255, null=True),
        ),
    ]
